### ISSUE TITLE
Helper Snippets

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/treehouse-design-system#17]
```css
<style>
p.clear.page_bottom_estimate_callout {
   display: none;
}
</style>
```
And then in notes: Paste in Advanced Head

If we want it removed from entire site must check Site Management > Exclude from Free Estimate Callouts
